# kubernetes/02-apps/bazarr/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: homelab
  labels:
    app.kubernetes.io/name: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bazarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bazarr
    spec:
      containers:
        - name: bazarr
          image: lscr.io/linuxserver/bazarr:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: homelab-common-vars # Para PUID, PGID, TZ
          ports:
            - name: http
              containerPort: 6767
              protocol: TCP
          volumeMounts:
            - name: bazarr-config
              mountPath: /config
            - name: media-movies-direct # Modificado
              mountPath: /movies
            - name: media-tv-direct     # Modificado
              mountPath: /tv
      volumes:
        - name: bazarr-config
          persistentVolumeClaim:
            claimName: bazarr-config-pvc # Usa local-path
        - name: media-movies-direct # Modificado
          hostPath:
            path: /mnt/usbmedia/movies
            type: Directory
        - name: media-tv-direct     # Modificado
          hostPath:
            path: /mnt/usbmedia/tv
            type: Directory