# kubernetes/02-apps/pgadmin/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
  namespace: homelab
  labels:
    app.kubernetes.io/name: pgadmin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: homelab-hostpath
  resources:
    requests:
      storage: 1Gi