# kubernetes/02-apps/pgadmin/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: homelab
  labels:
    app.kubernetes.io/name: pgadmin
type: Opaque
stringData:
  PGADMIN_DEFAULT_PASSWORD: "YOUR_PGADMIN_PASSWORD_REPLACE_ME"