# kubernetes/02-apps/homepage/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-config-pvc
  namespace: homelab # En tu namespace homelab
  labels:
    app.kubernetes.io/name: homepage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # La configuraci칩n de Homepage es peque침a, 1Gi es m치s que suficiente
  storageClassName: homelab-hostpath # Usar치 el provisionador por defecto de K3s