# kubernetes/02-apps/sonarr/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: homelab
  labels:
    app.kubernetes.io/name: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sonarr
    spec:
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:latest 
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: homelab-common-vars 
          ports:
            - name: http
              containerPort: 8989 
              protocol: TCP
          volumeMounts:
            - name: sonarr-config
              mountPath: /config 
            - name: media-tv-direct 
              mountPath: /tv    
            - name: media-downloads-direct
              mountPath: /downloads 
          # (Sondas Comentadas)
          # livenessProbe:
          #   httpGet:
          #     path: /api/v3/system/status 
          #     port: http
          #   initialDelaySeconds: 45
          #   periodSeconds: 20
          # readinessProbe:
          #   httpGet:
          #     path: /api/v3/system/status
          #     port: http
          #   initialDelaySeconds: 30
          #   periodSeconds: 15
      volumes:
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr-config-pvc
        - name: media-tv-direct 
          hostPath:
            path: /mnt/lab/media/tv 
            type: Directory
        - name: media-downloads-direct
          hostPath:
            path: /mnt/lab/media/downloads 
            type: Directory