# kubernetes/02-apps/radarr/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: homelab
  labels:
    app.kubernetes.io/name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radarr
    spec:
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest # O una versión específica (ej. :develop o :nightly si quieres probar)
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: homelab-common-vars # Para PUID, PGID, TZ
          ports:
            - name: http
              containerPort: 7878 # Puerto por defecto de la UI de Radarr
              protocol: TCP
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: media-movies-direct # Nuevo nombre para el volumeMount
              mountPath: /movies        # Sigue siendo /movies dentro del contenedor
            - name: media-downloads-direct # Nuevo nombre para el volumeMount
              mountPath: /downloads
      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config-pvc
        - name: media-movies-direct # Coincide con el volumeMount
          hostPath:
            path: /mnt/usbmedia/movies # Montaje directo
            type: Directory
        - name: media-downloads-direct # Coincide con el volumeMount
          hostPath:
            path: /mnt/usbmedia/downloads # Montaje directo
            type: Directory
