# kubernetes/02-apps/radarr/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: homelab
  labels:
    app.kubernetes.io/name: radarr
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radarr
        app.kubernetes.io/instance: radarr-prod
        app.kubernetes.io/version: "5.2.0"
        app.kubernetes.io/component: media-automation
        app.kubernetes.io/part-of: homelab
        app.kubernetes.io/managed-by: kubectl
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest 
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: homelab-common-vars 
          ports:
            - name: http
              containerPort: 7878 
              protocol: TCP
          volumeMounts:
            - name: radarr-config
              mountPath: /config 
            - name: media-movies-direct 
              mountPath: /movies 
            - name: media-downloads-direct
              mountPath: /downloads
          securityContext:
            allowPrivilegeEscalation: true
            runAsNonRoot: false
            runAsUser: 0
            capabilities:
              drop:
              - ALL
              add:
              - CHOWN
              - DAC_OVERRIDE
              - SETGID
              - SETUID
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config-pvc
        - name: media-movies-direct 
          hostPath:
            path: /mnt/lab/media/movies 
            type: Directory
        - name: media-downloads-direct
          hostPath:
            path: /mnt/lab/media/downloads 
            type: Directory