# kubernetes/02-apps/radarr/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: homelab
  labels:
    app.kubernetes.io/name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radarr
    spec:
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest # O una versión específica (ej. :develop o :nightly si quieres probar)
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: homelab-common-vars # Para PUID, PGID, TZ
          ports:
            - name: http
              containerPort: 7878 # Puerto por defecto de la UI de Radarr
              protocol: TCP
          volumeMounts:
            - name: radarr-config
              mountPath: /config # Ruta de configuración de Radarr
            - name: media-movies
              mountPath: /movies # Ruta donde Radarr gestionará las películas
              subPath: movies   # Monta la subcarpeta 'movies' del PVC 'homelab-media-pvc'
            - name: media-downloads
              mountPath: /downloads # Ruta donde Radarr buscará descargas completadas
              subPath: downloads   # Monta la subcarpeta 'downloads' del PVC 'homelab-media-pvc'
          # (Opcional) Sondas de Liveness y Readiness
          livenessProbe:
            httpGet:
              path: /api/v3/system/status # Endpoint de API de Radarr
              port: http
            initialDelaySeconds: 45
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /api/v3/system/status
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config-pvc
        - name: media-movies
          persistentVolumeClaim:
            claimName: homelab-media-pvc # PVC global para medios (en /mnt/usbmedia)
        - name: media-downloads
          persistentVolumeClaim:
            claimName: homelab-media-pvc # PVC global para medios (en /mnt/usbmedia)