# kubernetes/02-apps/radarr/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr-ingress
  namespace: homelab
  labels:
    app.kubernetes.io/name: radarr
  # annotations: # Eliminada anotación middleware y kubernetes.io/ingress.class
spec:
  ingressClassName: traefik # Añadido/Corregido
  rules:
    - host: radarr.homelab.local 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: radarr 
                port:
                  name: http # O number: 7878
# --- # Eliminada la definición del Middleware