# kubernetes/02-apps/qbittorrent/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: homelab
  labels:
    app.kubernetes.io/name: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: homelab-common-vars # Para PUID, PGID, TZ
          env:
            - name: QB_WEBUI_PORT
              value: "8080"
          ports:
            - name: http-webui
              containerPort: 8080 # Coincide con QB_WEBUI_PORT
              protocol: TCP
            - name: p2p-tcp # Puerto para conexiones TCP de torrents
              containerPort: 6881 # Puerto por defecto de qBittorrent
              protocol: TCP
            - name: p2p-udp # Puerto para conexiones UDP de torrents
              containerPort: 6881 # Puerto por defecto de qBittorrent
              protocol: UDP
          volumeMounts:
            - name: qbittorrent-config
              mountPath: /config # Ruta de configuración de qBittorrent
            - name: downloads-direct # Nuevo nombre para el volumeMount
              mountPath: /downloads   # Sigue siendo /downloads dentro del contenedor
          # (Sondas Comentadas Temporalmente)
          # livenessProbe:
          #   tcpSocket:
          #     port: http-webui
          #   initialDelaySeconds: 30
          #   periodSeconds: 15
          # readinessProbe:
          #   httpGet:
          #     path: / # O /login si existe
          #     port: http-webui
          #   initialDelaySeconds: 15
          #   periodSeconds: 10
      volumes:
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc # Usa el PVC local-path para la config
        - name: downloads-direct # Coincide con el volumeMount
          hostPath:
            path: /mnt/usbmedia/downloads # Montaje directo a la subcarpeta de descargas en el USB
            type: Directory # O DirectoryOrCreate si prefieres que K3s intente crearla