# kubernetes/02-apps/qbittorrent/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: homelab
  labels:
    app.kubernetes.io/name: qbittorrent
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qbittorrent
        app.kubernetes.io/instance: qbittorrent-prod
        app.kubernetes.io/version: "4.6.0"
        app.kubernetes.io/component: download-client
        app.kubernetes.io/part-of: homelab
        app.kubernetes.io/managed-by: kubectl
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:4.6.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: homelab-common-vars 
          env:
            - name: QB_WEBUI_PORT
              value: "8080"
            - name: WEBUI_USERNAME # Opcional, si quieres cambiar el usuario
              value: "admin"      # O tu usuario deseado
            - name: WEBUI_PASSWORD # Variable común para la contraseña de la UI en imágenes linuxserver
              valueFrom:
                secretKeyRef:
                  name: homelab-secrets
                  key: QB_PASSWORD
          ports:
            - name: http-webui
              containerPort: 8080 
              protocol: TCP
            - name: p2p-tcp 
              containerPort: 6881 
              protocol: TCP
            - name: p2p-udp 
              containerPort: 6881 
              protocol: UDP
          volumeMounts:
            - name: qbittorrent-config
              mountPath: /config 
            - name: downloads-direct 
              mountPath: /downloads
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
              - ALL
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            tcpSocket:
              port: http-webui
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http-webui
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc 
        - name: downloads-direct 
          hostPath:
            path: /mnt/lab/media/downloads 
            type: Directory