# kubernetes/02-apps/qbittorrent/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: homelab
  labels:
    app.kubernetes.io/name: qbittorrent
spec:
  replicas: 1
  # strategy: Recreate # Opcional: qBittorrent suele manejar bien RollingUpdate, pero Recreate es más simple si hay problemas.
  selector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest # O una versión específica
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: homelab-common-vars # Para PUID, PGID, TZ
          env:
            - name: QB_WEBUI_PORT # Puerto interno para la WebUI dentro del contenedor
              value: "8080" 
            # La contraseña se inyectará como una variable de entorno real por Kubernetes
            # pero la imagen de linuxserver/qbittorrent no la usa directamente de una variable QB_PASSWORD.
            # La contraseña se establece en la UI o en el archivo de configuración.
            # Lo que SÍ podemos hacer es usar el ConfigMap para otros ajustes si es necesario,
            # o un script de inicio si quisiéramos automatizar el seteo de contraseña,
            # pero para qBittorrent, es más común configurarlo vía UI o su archivo de config.
            # El secret QB_PASSWORD lo recordaremos para configurar la UI manualmente la primera vez.
          ports:
            - name: http-webui
              containerPort: 8080 # Coincide con QB_WEBUI_PORT
              protocol: TCP
            - name: p2p-tcp # Puerto para conexiones TCP de torrents
              containerPort: 6881 # Puerto por defecto de qBittorrent
              protocol: TCP
            - name: p2p-udp # Puerto para conexiones UDP de torrents (DHT, PeX, rastreadores UDP)
              containerPort: 6881 # Puerto por defecto de qBittorrent
              protocol: UDP
          volumeMounts:
            - name: qbittorrent-config
              mountPath: /config # Ruta de configuración de qBittorrent
            - name: media-downloads
              mountPath: /downloads # Ruta donde qBittorrent guardará las descargas
              subPath: downloads   # Monta la subcarpeta 'downloads' del PVC 'homelab-media-pvc'
          # (Opcional) Sondas de Liveness y Readiness
          livenessProbe:
            tcpSocket: # Intenta conectar al puerto de la WebUI
              port: http-webui
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet: # Intenta obtener la página de login
              path: /
              port: http-webui
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: media-downloads
          persistentVolumeClaim:
            claimName: homelab-media-pvc # PVC global para medios (en /mnt/usbmedia)