# kubernetes/02-apps/qbittorrent/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: homelab
  labels:
    app.kubernetes.io/name: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: homelab-common-vars 
          env:
            - name: QB_WEBUI_PORT
              value: "8080" 
          ports:
            - name: http-webui
              containerPort: 8080 
              protocol: TCP
            - name: p2p-tcp 
              containerPort: 6881 
              protocol: TCP
            - name: p2p-udp 
              containerPort: 6881 
              protocol: UDP
          volumeMounts:
            - name: qbittorrent-config
              mountPath: /config 
            - name: downloads-direct 
              mountPath: /downloads   
          # (Sondas Comentadas)
          # livenessProbe:
          #   tcpSocket: 
          #     port: http-webui
          #   initialDelaySeconds: 30
          #   periodSeconds: 15
          # readinessProbe:
          #   httpGet: 
          #     path: /
          #     port: http-webui
          #   initialDelaySeconds: 15
          #   periodSeconds: 10
      volumes:
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc 
        - name: downloads-direct 
          hostPath:
            path: /mnt/lab/media/downloads 
            type: Directory