# kubernetes/02-apps/qbittorrent/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent-ingress
  namespace: homelab
  labels:
    app.kubernetes.io/name: qbittorrent
  # annotations: # Eliminada anotación kubernetes.io/ingress.class
spec:
  ingressClassName: traefik # Añadido/Corregido
  rules:
    - host: qb.homelab.local 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qbittorrent-webui 
                port:
                  name: http-webui # O number: 8080