# kubernetes/00-base/secrets.template.yaml
apiVersion: v1
kind: Secret
metadata:
  name: homelab-secrets
  namespace: homelab # En tu namespace homelab
type: Opaque # Tipo de secreto genérico
stringData: # Usar stringData es conveniente para valores legibles (se codificarán a base64 automáticamente por Kubernetes)
  # qBittorrent
  QB_PASSWORD: "YOUR_QBITTORRENT_PASSWORD_REPLACE_ME"

  # PostgreSQL
  POSTGRES_USER: "homelabadmin" # Puedes definir un usuario aquí o usar el por defecto de la imagen
  POSTGRES_PASSWORD: "YOUR_POSTGRES_PASSWORD_REPLACE_ME"
  # POSTGRES_DB: "homelabdb" # Puedes definir una DB por defecto aquí si quieres

  # MongoDB
  MONGO_INITDB_ROOT_USERNAME: "YOUR_MONGO_USER_REPLACE_ME"
  MONGO_INITDB_ROOT_PASSWORD: "YOUR_MONGO_PASSWORD_REPLACE_ME"

  # Plex
  PLEX_CLAIM_TOKEN: "YOUR_PLEX_CLAIM_TOKEN_REPLACE_ME" # Recuerda que este es de corta duración

  # (Opcional) API Keys para otras aplicaciones, si las tienes
  # RADARR_API_KEY: "YOUR_RADARR_API_KEY_REPLACE_ME" # Ejemplo si alguna app necesitara la API Key de otra
  # SONARR_API_KEY: "YOUR_SONARR_API_KEY_REPLACE_ME" # Ejemplo


  PIHOLE_WEBPASSWORD: "YOUR_PIHOLE_WEBPAASWORD_REPLACE_ME"