# kubernetes/00-base/secrets-improved.template.yaml
# IMPORTANTE: Este archivo es una plantilla. 
# 1. Copia este archivo como 'secrets.yaml'
# 2. Reemplaza todos los valores REPLACE_ME con valores reales
# 3. NUNCA commitees el archivo secrets.yaml a git
# 4. Considera usar Sealed Secrets o External Secrets Operator en producción
---
apiVersion: v1
kind: Secret
metadata:
  name: homelab-secrets
  namespace: homelab
  labels:
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: kubectl
type: Opaque
data:
  # qBittorrent
  # Genera con: echo -n "tu-contraseña" | base64
  QB_PASSWORD: "WU9VUl9RQklUVE9SUkVOVF9QQVNTV09SRF9SRVBMQUNFX01F"
  
  # PostgreSQL
  # Usuario por defecto: homelabadmin
  POSTGRES_USER: "aG9tZWxhYmFkbWlu"
  # Genera contraseña segura: openssl rand -base64 32
  POSTGRES_PASSWORD: "WU9VUl9QT1NUR1JFU19QQVNTV09SRF9SRVBMQUNFX01F"
  
  # MongoDB
  # Usuario root
  MONGO_INITDB_ROOT_USERNAME: "WU9VUl9NT05HT19VU0VSX1JFUExBQ0VfTUU="
  # Genera contraseña segura: openssl rand -base64 32
  MONGO_INITDB_ROOT_PASSWORD: "WU9VUl9NT05HT19QQVNTV09SRF9SRVBMQUNFX01F"
  
  # Plex
  # Obtén el token de: https://www.plex.tv/claim/
  # NOTA: Este token expira en 4 minutos, úsalo rápidamente
  PLEX_CLAIM_TOKEN: "WU9VUl9QTEVYX0NMQUlNX1RPS0VOX1JFUExBQ0VfTUU="
  
  # Pi-hole
  # Contraseña para la interfaz web
  PIHOLE_WEBPASSWORD: "WU9VUl9QSUhPTEVfV0VCUEFBU1dPUkRfUkVQTEFDRV9NRQ=="
  
---
# Secretos adicionales para las nuevas aplicaciones
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: homelab
  labels:
    app.kubernetes.io/name: pgadmin
    app.kubernetes.io/part-of: homelab
type: Opaque
data:
  # Contraseña para pgAdmin
  PGADMIN_DEFAULT_PASSWORD: "WU9VUl9QR0FETUlOX1BBU1NXT1JEX1JFUExBQ0VfTUU="
  
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
  namespace: homelab
  labels:
    app.kubernetes.io/name: mongo-express
    app.kubernetes.io/part-of: homelab
type: Opaque
data:
  # Contraseña para autenticación básica de Mongo Express
  ME_CONFIG_BASICAUTH_PASSWORD: "WU9VUl9NT05HT19FWFBSRVNTX1BBU1NXT1JEX1JFUExBQ0VfTUU="