# kubernetes/02-apps/mongo-express/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
  namespace: homelab
  labels:
    app.kubernetes.io/name: mongo-express
type: Opaque
stringData:
  ME_CONFIG_BASICAUTH_PASSWORD: "YOUR_MONGO_EXPRESS_PASSWORD_REPLACE_ME"