# kubernetes/04-network-policies/01-allow-dns.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-homelab # O allow-dns-external-homelab si prefieres un nombre más específico
  namespace: homelab
spec:
  podSelector: {} # Se aplica a todos los Pods en el namespace 'homelab'
  policyTypes:
    - Egress
  egress:
    - ports: # Permite el egreso a cualquier destino en estos puertos
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
      # Al no especificar un selector 'to' aquí, se permite el egreso a cualquier IP en estos puertos.
      # Si quieres ser más restrictivo, podrías añadir un bloque 'to' con 'ipBlock'
      # para especificar CIDRs permitidos, por ejemplo, para 1.1.1.1 y 1.0.0.1.
      # Ejemplo para IPs específicas:
      # to:
      #   - ipBlock:
      #       cidr: 1.1.1.1/32
      #   - ipBlock:
      #       cidr: 1.0.0.1/32
      #   - ipBlock: # Añade otros servidores DNS que Pi-hole podría usar, ej., los de Google
      #       cidr: 8.8.8.8/32
      #   - ipBlock:
      #       cidr: 8.8.4.4/32