# kubernetes/02-apps/plex/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: homelab
  labels:
    app.kubernetes.io/name: plex
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: plex
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plex
        app.kubernetes.io/instance: plex-prod
        app.kubernetes.io/version: "1.40.0"
        app.kubernetes.io/component: media-server
        app.kubernetes.io/part-of: homelab
        app.kubernetes.io/managed-by: kubectl
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: plex
          image: lscr.io/linuxserver/plex:1.40.0 
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: homelab-common-vars 
          env:
            - name: PLEX_CLAIM
              valueFrom:
                secretKeyRef:
                  name: homelab-secrets
                  key: PLEX_CLAIM_TOKEN
            - name: VERSION 
              value: "docker" 
          ports:
            - name: http-plex 
              containerPort: 32400
              protocol: TCP
            # ... (otros puertos de Plex si los necesitas en el service) ...
          volumeMounts:
            - name: plex-config
              mountPath: /config 
            - name: media-movies-direct 
              mountPath: /data/movies
            - name: media-tv-direct     
              mountPath: /data/tvshows
            # - name: transcode 
            #   mountPath: /transcode 
            # - name: dev-dri
            #   mountPath: /dev/dri
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
              - ALL
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          startupProbe:
            httpGet:
              path: /identity
              port: http-plex
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /identity
              port: http-plex
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /identity
              port: http-plex
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: plex-config
          persistentVolumeClaim:
            claimName: plex-config-pvc
        - name: media-movies-direct 
          hostPath:
            path: /mnt/lab/media/movies
            type: Directory
        - name: media-tv-direct     
          hostPath:
            path: /mnt/lab/media/tv
            type: Directory
        # - name: transcode 
        #   emptyDir: {} 
        # - name: dev-dri
        #   hostPath:
        #     path: /dev/dri