apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: homelab
  labels:
    app.kubernetes.io/name: plex
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: plex
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plex
    spec:
      containers:
        - name: plex
          image: lscr.io/linuxserver/plex:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: homelab-common-vars
          env:
            - name: PLEX_CLAIM
              valueFrom:
                secretKeyRef:
                  name: homelab-secrets
                  key: PLEX_CLAIM_TOKEN
            - name: VERSION
              value: "docker"
          ports:
            - name: http-plex
              containerPort: 32400
            # ... (otros puertos de Plex si los necesitas expuestos en el service)
          volumeMounts:
            - name: plex-config
              mountPath: /config
            - name: media-movies-direct # Modificado
              mountPath: /data/movies
            - name: media-tv-direct     # Modificado
              mountPath: /data/tvshows
            # - name: transcode
            #   mountPath: /transcode
            # - name: dev-dri # Para QSV
            #   mountPath: /dev/dri
          # (Sondas Comentadas Temporalmente)
          # livenessProbe:
          #   httpGet:
          #     path: /identity
          #     port: http-plex
          #   initialDelaySeconds: 60
          #   periodSeconds: 20
          #   timeoutSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /identity
          #     port: http-plex
          #   initialDelaySeconds: 45
          #   periodSeconds: 15
          #   timeoutSeconds: 5
          # (Security Context para QSV si es necesario)
          # securityContext:
          #   privileged: true
      volumes:
        - name: plex-config
          persistentVolumeClaim:
            claimName: plex-config-pvc # Usa local-path para la config
        - name: media-movies-direct # Modificado
          hostPath:
            path: /mnt/usbmedia/movies
            type: Directory
        - name: media-tv-direct     # Modificado
          hostPath:
            path: /mnt/usbmedia/tv
            type: Directory
        # - name: transcode
        #   emptyDir: {}
        # - name: dev-dri # Para QSV
        #   hostPath:
        #     path: /dev/dri
        #     type: Directory # O CharDevice si es un solo dispositivo