# kubernetes/02-apps/plex/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-ingress
  namespace: homelab
  labels:
    app.kubernetes.io/name: plex
  # annotations: # Eliminada anotación kubernetes.io/ingress.class
    # traefik.ingress.kubernetes.io/customrequestheaders: X-Forwarded-Proto":"https" # Puede quedarse si es necesaria
spec:
  ingressClassName: traefik # Añadido/Corregido
  rules:
    - host: plex.homelab.local 
      http:
        paths:
          - path: / 
            pathType: Prefix
            backend:
              service:
                name: plex 
                port:
                  name: http-plex # O number: 32400