# kubernetes/02-apps/jellyfin/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: homelab
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: homelab-common-vars # Para PUID, PGID, TZ
          ports:
            - name: http
              containerPort: 8096 # Puerto HTTP principal de Jellyfin
              protocol: TCP
            - name: dlna-http # Aunque en el service lo llamamos https-alt, este es el target
              containerPort: 8920
              protocol: TCP
            - name: discovery-udp
              containerPort: 7359
              protocol: UDP
            - name: dlna-ssdp
              containerPort: 1900
              protocol: UDP
          volumeMounts:
            - name: jellyfin-config
              mountPath: /config # Ruta de configuración de Jellyfin
            - name: media-movies-direct # Modificado
              mountPath: /data/movies    # Donde Jellyfin buscará películas
            - name: media-tv-direct     # Modificado
              mountPath: /data/tvshows   # Donde Jellyfin buscará series
            # (Opcional) Para transcodificación por hardware QSV
            # - name: dev-dri
            #   mountPath: /dev/dri
          # (Sondas Comentadas Temporalmente)
          # El endpoint /health de Jellyfin debería ser no autenticado, pero lo comentamos por ahora.
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          #   initialDelaySeconds: 45
          #   periodSeconds: 20
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          #   initialDelaySeconds: 30
          #   periodSeconds: 15
          # (Security Context para QSV si es necesario)
          # securityContext:
          #   privileged: true
      volumes:
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-config-pvc # Usa local-path para la config
        - name: media-movies-direct # Modificado
          hostPath:
            path: /mnt/usbmedia/movies # Montaje directo
            type: Directory
        - name: media-tv-direct     # Modificado
          hostPath:
            path: /mnt/usbmedia/tv     # Montaje directo
            type: Directory
        # (Opcional) Para transcodificación por hardware QSV
        # - name: dev-dri
        #   hostPath:
        #     path: /dev/dri
        #     type: Directory # O el tipo correcto para el dispositivo