# kubernetes/02-apps/jellyfin/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: homelab
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: homelab-common-vars
          ports:
            - name: http
              containerPort: 8096
              protocol: TCP
            - name: dlna-http 
              containerPort: 8920 
              protocol: TCP 
            - name: discovery-udp
              containerPort: 7359
              protocol: UDP
            - name: dlna-ssdp
              containerPort: 1900
              protocol: UDP
          volumeMounts:
            - name: jellyfin-config
              mountPath: /config
            - name: media-movies-direct 
              mountPath: /data/movies    
            - name: media-tv-direct     
              mountPath: /data/tvshows   
            # - name: dev-dri 
            #   mountPath: /dev/dri
          # (Sondas Comentadas)
          # livenessProbe:
          #   httpGet:
          #     path: /health 
          #     port: http
          #   initialDelaySeconds: 45
          #   periodSeconds: 20
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          #   initialDelaySeconds: 30
          #   periodSeconds: 15
      volumes:
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-config-pvc
        - name: media-movies-direct 
          hostPath:
            path: /mnt/usbmedia/movies
            type: Directory
        - name: media-tv-direct     
          hostPath:
            path: /mnt/usbmedia/tv
            type: Directory
        # - name: dev-dri 
        #   hostPath:
        #     path: /dev/dri