# kubernetes/02-apps/jellyfin/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: homelab
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:latest # O una versión específica
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: homelab-common-vars # Para PUID, PGID, TZ
          ports:
            - name: http
              containerPort: 8096 # Puerto HTTP principal de Jellyfin
              protocol: TCP
            # Puertos adicionales para DLNA y descubrimiento (opcionales si no los usas)
            - name: dlna-http 
              containerPort: 8920 # Puerto HTTPS (Jellyfin lo usa también para algunas cosas de DLNA/companion)
              protocol: TCP 
            - name: discovery-udp
              containerPort: 7359
              protocol: UDP
            - name: dlna-ssdp
              containerPort: 1900
              protocol: UDP
          volumeMounts:
            - name: jellyfin-config
              mountPath: /config # Ruta de configuración de Jellyfin
            - name: media-movies
              mountPath: /data/movies # Ruta donde Jellyfin buscará películas
              subPath: movies        # Monta la subcarpeta 'movies' del PVC 'homelab-media-pvc'
            - name: media-tv
              mountPath: /data/tvshows # Ruta donde Jellyfin buscará series
              subPath: tv             # Monta la subcarpeta 'tv' del PVC 'homelab-media-pvc'
            # Añade más montajes si tienes otras bibliotecas (música, fotos, etc.)
            # - name: media-music
            #   mountPath: /data/music
            #   subPath: music # Asumiendo que tienes /mnt/usbmedia/music
          # (Opcional pero recomendado para transcodificación por hardware en Mini PC con Intel QSV)
          # devices:
          #   - hostPath: /dev/dri/renderD128 # O el dispositivo render correcto
          #     devicePath: /dev/dri/renderD128
          # securityContext: # Si se usa 'devices', a veces es necesario un contexto privilegiado o capacidades específicas.
          #   privileged: true # Usar con precaución. Alternativamente, investiga las group-add o capabilities necesarias.
          livenessProbe:
            httpGet:
              path: /health # Endpoint de salud de Jellyfin
              port: http
            initialDelaySeconds: 45
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
      volumes:
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-config-pvc
        - name: media-movies
          persistentVolumeClaim:
            claimName: homelab-media-pvc # PVC global para medios
        - name: media-tv
          persistentVolumeClaim:
            claimName: homelab-media-pvc
        # - name: media-music # Si añadiste montaje para música
        #   persistentVolumeClaim:
        #     claimName: homelab-media-pvc