# kubernetes/02-apps/jellyfin/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-ingress
  namespace: homelab
  labels:
    app.kubernetes.io/name: jellyfin
  annotations:
    # kubernetes.io/ingress.class: "traefik" # Eliminada o comentada
    traefik.ingress.kubernetes.io/customrequestheaders: X-Forwarded-Proto":"https" # Puede quedarse si la necesitas
spec:
  ingressClassName: traefik # Añadido/Corregido
  rules:
    - host: jellyfin.homelab.local 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin 
                port:
                  name: http # O number: 8096