# kubernetes/02-apps/jackett/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: homelab
  labels:
    app.kubernetes.io/name: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jackett
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jackett
    spec:
      containers:
        - name: jackett
          image: lscr.io/linuxserver/jackett:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: homelab-common-vars 
          ports:
            - name: http
              containerPort: 9117
              protocol: TCP
          volumeMounts:
            - name: jackett-config
              mountPath: /config
            - name: media-downloads-direct # Modificado
              mountPath: /downloads
          # (Sondas Comentadas)
          # livenessProbe:
          #   httpGet:
          #     path: /UI/Dashboard
          #     port: http
          #   initialDelaySeconds: 30
          #   periodSeconds: 20
          # readinessProbe:
          #   httpGet:
          #     path: /UI/Dashboard
          #     port: http
          #   initialDelaySeconds: 15
          #   periodSeconds: 15
      volumes:
        - name: jackett-config
          persistentVolumeClaim:
            claimName: jackett-config-pvc 
        - name: media-downloads-direct # Modificado
          hostPath:
            path: /mnt/storage2tb/homelab/media/downloads 
            type: Directory