# kubernetes/02-apps/jackett/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config-pvc
  namespace: homelab # En tu namespace homelab
  labels:
    app.kubernetes.io/name: jackett
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # La configuración de Jackett es relativamente pequeña
  storageClassName: homelab-hostpath # Usará el provisionador por defecto de K3s