# kubernetes/02-apps/pdbs/critical-services-pdbs.yaml
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: plex-pdb
  namespace: homelab
  labels:
    app.kubernetes.io/name: plex
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: plex
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: jellyfin-pdb
  namespace: homelab
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgresql-pdb
  namespace: homelab
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mongodb-pdb
  namespace: homelab
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pihole-pdb
  namespace: homelab
  labels:
    app.kubernetes.io/name: pihole
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pihole
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: qbittorrent-pdb
  namespace: homelab
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent